# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: yarn lint
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run:
          name: Authenticate
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            git config --global -l
            git config --global user.email pc@paulocunha.me
            git config --global user.name pmrcunha
            git remote --v
      - run:
          name: Bump version
          command: |
            yarn config set version-tag-prefix ""
            yarn config set version-git-message "Bumped version to v%s"
            yarn version --new-version patch
      - run:
          name: Push new version number
          command: |
            git checkout -b bump-version
            git add package.json
            git commit -m 'bump version'
            git push --follow-tags origin bump-version
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
